import { Employee, Vehicle, Settings, UserRental } from './types';

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Raj Patel',
    email: 'rajpatel@co.com',
    department: 'Engineering',
    manager: 'A. Shah',
    location: 'Ahmedabad',
    platformAccess: 'Granted',
    mobileNumber: '+91 98250 12345',
    memberSince: '15-Jan-2023',
  },
  {
    id: 'emp-2',
    name: 'Krishna Singh',
    email: 'krishna.s@co.com',
    department: 'Sales',
    manager: 'R. Mehta',
    location: 'Ahmedabad',
    platformAccess: 'Granted',
    mobileNumber: '+91 98790 54321',
    memberSince: '04-Nov-2023',
  },
  {
    id: 'emp-3',
    name: 'Priya Nair',
    email: 'priya.nair@co.com',
    department: 'HR',
    manager: 'A. Shah',
    location: 'Gandhinagar',
    platformAccess: 'Revoked',
    mobileNumber: '+91 94260 98765',
    memberSince: '20-May-2024',
  },
  {
    id: 'emp-4',
    name: 'Amit Sharma',
    email: 'amit.sharma@co.com',
    department: 'Engineering',
    manager: 'A. Shah',
    location: 'Ahmedabad',
    platformAccess: 'Granted',
    mobileNumber: '+91 99123 45678',
    memberSince: '12-Feb-2024',
  },
  {
    id: 'emp-5',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@co.com',
    department: 'Marketing',
    manager: 'S. Sharma',
    location: 'Ahmedabad',
    platformAccess: 'Granted',
    mobileNumber: '+91 98989 12345',
    memberSince: '08-Aug-2023',
  },
  {
    id: 'emp-6',
    name: 'Vikram Malhotra',
    email: 'vikram.m@co.com',
    department: 'Operations',
    manager: 'R. Mehta',
    location: 'Gandhinagar',
    platformAccess: 'Granted',
    mobileNumber: '+91 97234 56789',
    memberSince: '19-Sep-2023',
  },
  {
    id: 'emp-7',
    name: 'Pooja Patel',
    email: 'pooja.patel@co.com',
    department: 'Sales',
    manager: 'R. Mehta',
    location: 'Ahmedabad',
    platformAccess: 'Granted',
    mobileNumber: '+91 96012 34567',
    memberSince: '25-Dec-2022',
  },
  {
    id: 'emp-8',
    name: 'Rohan Joshi',
    email: 'rohan.joshi@co.com',
    department: 'Engineering',
    manager: 'A. Shah',
    location: 'Ahmedabad',
    platformAccess: 'Granted',
    mobileNumber: '+91 95555 12345',
    memberSince: '30-May-2024',
  },
  {
    id: 'emp-9',
    name: 'Aarti Mehta',
    email: 'aarti.mehta@co.com',
    department: 'HR',
    manager: 'S. Sharma',
    location: 'Gandhinagar',
    platformAccess: 'Revoked',
    mobileNumber: '+91 94444 67890',
    memberSince: '14-Mar-2024',
  },
  {
    id: 'emp-10',
    name: 'Devendra Vyas',
    email: 'devendra.vyas@co.com',
    department: 'Finance',
    manager: 'K. Patel',
    location: 'Ahmedabad',
    platformAccess: 'Granted',
    mobileNumber: '+91 93333 54321',
    memberSince: '01-Jan-2024',
  },
  {
    id: 'emp-11',
    name: 'Harish Kumar',
    email: 'harish.k@co.com',
    department: 'Operations',
    manager: 'K. Patel',
    location: 'Ahmedabad',
    platformAccess: 'Granted',
    mobileNumber: '+91 92222 98765',
    memberSince: '15-May-2023',
  },
  {
    id: 'emp-12',
    name: 'Nidhi Shah',
    email: 'nidhi.shah@co.com',
    department: 'Sales',
    manager: 'R. Mehta',
    location: 'Gandhinagar',
    platformAccess: 'Granted',
    mobileNumber: '+91 91111 23456',
    memberSince: '10-Oct-2023',
  },
];

export const initialVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    registrationNumber: 'GJ01AB1234',
    model: 'Swift Dzire',
    seatingCapacity: 4,
    driver: 'Raj Patel',
    status: 'Active',
  },
  {
    id: 'veh-2',
    registrationNumber: 'GJ01AB5034',
    model: 'Alto 800',
    seatingCapacity: 3,
    driver: 'Krishna Singh',
    status: 'Active',
  },
  {
    id: 'veh-3',
    registrationNumber: 'GJ01CD7788',
    model: 'Innova Crysta',
    seatingCapacity: 6,
    driver: 'Priya Nair',
    status: 'Inactive',
  },
  {
    id: 'veh-4',
    registrationNumber: 'GJ01EF9922',
    model: 'Honda City',
    seatingCapacity: 4,
    driver: 'Amit Sharma',
    status: 'Active',
  },
  {
    id: 'veh-5',
    registrationNumber: 'GJ01GH4411',
    model: 'Hyundai i20',
    seatingCapacity: 4,
    driver: 'Sneha Reddy',
    status: 'Active',
  },
  {
    id: 'veh-6',
    registrationNumber: 'GJ01JK5566',
    model: 'Tata Nexon',
    seatingCapacity: 4,
    driver: 'Vikram Malhotra',
    status: 'Active',
  },
  {
    id: 'veh-7',
    registrationNumber: 'GJ01LM8899',
    model: 'Mahindra XUV700',
    seatingCapacity: 6,
    driver: 'Pooja Patel',
    status: 'Active',
  },
  {
    id: 'veh-8',
    registrationNumber: 'GJ01NP1122',
    model: 'Kia Seltos',
    seatingCapacity: 4,
    driver: 'Rohan Joshi',
    status: 'Active',
  },
  {
    id: 'veh-9',
    registrationNumber: 'GJ01QR3344',
    model: 'Maruti WagonR',
    seatingCapacity: 4,
    driver: 'Aarti Mehta',
    status: 'Inactive',
  },
  {
    id: 'veh-10',
    registrationNumber: 'GJ01ST5566',
    model: 'Hyundai Creta',
    seatingCapacity: 4,
    driver: 'Devendra Vyas',
    status: 'Active',
  },
  {
    id: 'veh-11',
    registrationNumber: 'GJ01UV7788',
    model: 'Toyota Fortuner',
    seatingCapacity: 6,
    driver: 'Harish Kumar',
    status: 'Active',
  },
  {
    id: 'veh-12',
    registrationNumber: 'GJ01WX9900',
    model: 'Honda Amaze',
    seatingCapacity: 4,
    driver: 'Nidhi Shah',
    status: 'Active',
  },
];

export const initialSettings: Settings = {
  companyName: 'Odoo Pvt. Ltd.',
  industry: 'Software',
  registeredAddress: 'Gandhinagar',
  adminContact: 'admin@odoo.com',
  registeredEmployees: 48,
  fuelCost: 96.50,
  costPerKm: 8.00,
  travelCostOperational: 2.50,
};

export const initialUserRentals: UserRental[] = [
  {
    id: 'rent-1',
    userName: 'Raj Patel',
    vehicleModel: 'Swift Dzire',
    vehicleReg: 'GJ01AB1234',
    dateUsed: '2026-07-18',
    timeRented: '09:00 AM - 05:00 PM',
    locationUsed: 'Ahmedabad',
  },
  {
    id: 'rent-2',
    userName: 'Krishna Singh',
    vehicleModel: 'Alto 800',
    vehicleReg: 'GJ01AB5034',
    dateUsed: '2026-07-17',
    timeRented: '10:30 AM - 02:30 PM',
    locationUsed: 'Ahmedabad',
  },
  {
    id: 'rent-3',
    userName: 'Priya Nair',
    vehicleModel: 'Innova Crysta',
    vehicleReg: 'GJ01CD7788',
    dateUsed: '2026-07-15',
    timeRented: '08:00 AM - 08:00 PM',
    locationUsed: 'Gandhinagar',
  },
  {
    id: 'rent-4',
    userName: 'Amit Sharma',
    vehicleModel: 'Honda City',
    vehicleReg: 'GJ01EF9922',
    dateUsed: '2026-07-14',
    timeRented: '09:00 AM - 06:00 PM',
    locationUsed: 'Ahmedabad',
  },
  {
    id: 'rent-5',
    userName: 'Sneha Reddy',
    vehicleModel: 'Hyundai i20',
    vehicleReg: 'GJ01GH4411',
    dateUsed: '2026-07-12',
    timeRented: '11:00 AM - 04:00 PM',
    locationUsed: 'Ahmedabad',
  },
];
